### ISSUE TITLE
Bug: Timezone feature does not work

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#645]
### Describe the bug.

When I clicked on the selected timezone, it takes me to search timezone and when I input my country it didn't work.

### Steps to reproduce.

* Launch the app.

* Clicked on menu icon.

* Then, click on utilities

* Scroll down and click on the world clock

* Then select timezone

* And note the bug

### Expected Behaviour

I was expecting to be able to select timezone of my country when I click on the selected one

### Screen recording
https://youtu.be/UFTV9LxXLAo

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [5.5.0]

**Comment by ShivangiSingh17** [comment]
@darewealth, that would be a version problem as you are even not able to access the droplist of the countries list. It is working for me in the app properly.

**Comment by malieop** [comment]
Is anyone resolving this issue ??

**Comment by Swati4star** [comment]
Do you want to? @malieop

**Comment by malieop** [comment]
I can ... how do u want it ?
Like a list ? and the user can choose one timezone?

**Comment by malieop** [comment]
@Swati4star I just can't get some of the flags right, because to get the timezones data I had to use the Java Timezone class and the method that search for the flag also needs to be updated to this cases where the Android API is lower... I will do the Pull Request like this, it works! Only don't show sone flags
