### ISSUE TITLE
App crashed when i select and crop image for profile.

### ISSUE THREAD

**Issue by darewealth** [project-travel-mate/Travel-Mate#691]
Describe the bug.
When I tried to select an image for my profile I clicked on the upload and the complete action. I selected the image I want to use and click on the crop function immediately I clicked on crop the app crashed.

### Screen recording.
https://youtu.be/cwIxaIMT6_8

### Devices and Versions)

* Device: [Gionee, X1]

* Version [7.0]

* App version [5.5.0]

**Comment by sukhbeer** [comment]
@Swati4star Can I work on this?

**Comment by Swati4star** [comment]
Sure @sukhbeer 👍

**Comment by sukhbeer** [comment]
@Swati4star I tried a different method for that issue but I didn't find anything wrong with that everything works fine I also test application in android version 7.0 there is no issue. if logcat detailed are provided for this it will be more clear.

Instead of this, I found that when we select or set image in profile and reopen application again user image not appear in navigation drawer and profile Activity also and found this error.
![Screenshot (29)](https://user-images.githubusercontent.com/25095372/63521123-7d5fed80-c513-11e9-8449-2e288802e5e8.png)
should I post this as an issue

**Comment by Swati4star** [comment]
@sukhbeer Then, what did changes you open up these Pull requests with?

regarding the error you posted, is the application crashing here? or you are just seeing this error?

**Comment by sukhbeer** [comment]
@Swati4star sorry late reply I close the pull request few days ago. I don't see any error with default select image code.
regarding the error app not crashing here. This error come when user select or set image in profile and re-open application again user image is disappear as I earlier mentioned and I also share video

https://youtu.be/0MlIqhsre4o

**Comment by prabhakar267** [comment]
@sukhbeer This seems to be a different issue than the one described here, please open a new issue. Closing this one since this seems to be fixed.
@darewealth Feel free to reopen if it isn't fixed
